app/models/senders.py
from .. import db
from datetime import datetime
from flask import current_app
from app.models.roles import Role


class Sender(db.Model):
    __tablename__ = "senders"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    user_id = db.Column(db.Integer(), db.ForeignKey("users.id"))
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(
        db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow
    )

    def __repr__(self):
        return '<Sender \'%s\'>' % self.title

app/sender/forms.py
from flask import url_for
from flask_wtf import Form, FlaskForm
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms import ValidationError
from wtforms.fields import (
    BooleanField,
    PasswordField,
    StringField,
    SubmitField,
    TextField,
    DateField,
    DecimalField,
    SelectField,
    TextAreaField,
    IntegerField,
    FileField)
from wtforms import RadioField
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length, DataRequired
from flask_wtf.file import FileField, FileRequired, FileAllowed
from flask_uploads import UploadSet, configure_uploads, DOCUMENTS, IMAGES, TEXT
from flask_login import current_user
from app.models import User
from app.models import *

certificates = UploadSet("certificates", TEXT + DOCUMENTS + IMAGES)


def get_pk(obj):
    return str(obj)


class ReviewForm(FlaskForm):
    stars = RadioField('Label', coerce=int)
    comment = TextAreaField(
        'Comment', validators=[InputRequired(),
                               Length(1, 300)])
    submit = SubmitField('Submit')

#
# class MessageForm(Form):
#     message = TextAreaField(
#         "Message", validators=[DataRequired(), Length(min=0, max=140)]
#     )
#     submit = SubmitField("Submit")


class ProfileForm(FlaskForm):
    first_name = StringField(
        'First name', validators=[InputRequired(),
                                  Length(1, 64)])
    surname = StringField(
        'Surname', validators=[InputRequired(),
                               Length(1, 64)])
    email = EmailField(
        'Email', validators=[InputRequired(),
                             Length(1, 64),
                             Email()])
    address = StringField('Address')
    dob = DateField('Date Of Birth', validators=[DataRequired()], format='%d/%m/%Y')

    submit = SubmitField('Submit')


class PersonalDetailsForm(FlaskForm):
    title = StringField(
        'Title')
    first_name = StringField(
        'First name', validators=[InputRequired(),
                                  Length(1, 64)])
    surname = StringField(
        'Surname', validators=[InputRequired(),
                               Length(1, 64)])
    second_name = StringField(
        'Second name', validators=[InputRequired(),
                                   Length(1, 64)])
    gender = SelectField(validators=[DataRequired()],
                         choices=[('male', 'MALE'), ('female', 'FEMALE')])
    pob = StringField(
        'Place Of Birth', validators=[InputRequired(),
                                      Length(1, 100)])
    dob = DateField('Date Of Birth', validators=[DataRequired()], format='%d/%m/%Y')

    civil_status = SelectField(validators=[DataRequired()],
                               choices=[('cohabitation', 'Cohabitation'), ('divorced', 'Divorced'),
                                        ('domestic_partner', 'Domestic Partner'),
                                        ('legally_separated', 'Legally Separated'), ('married', 'Married'),
                                        ('separated', 'Separated'), ('single', 'Single'),
                                        ('undetermined', 'Undetermined')])
    nationality = StringField(
        'Nationality', validators=[InputRequired(),
                                   Length(1, 64)])
    disability = SelectField(
                             choices=[('yes', 'YES'), ('no', 'NO')])
    disability_nature = StringField(
        'Disability Nature')
    disability_registration_details = StringField(
        'Disability Registration Details')

    submit = SubmitField('Submit')


class ContactInfoForm(FlaskForm):
    email = EmailField(
        'Email', validators=[InputRequired(),
                             Length(1, 64),
                             Email()])
    address = StringField(
        'Address', validators=[InputRequired(),
                               Length(1, 64)])
    county = StringField(
        'County', validators=[InputRequired(),
                              Length(1, 64)])
    phone_number_personal = StringField(
        'Mobile Number', validators=[InputRequired(),
                                     Length(1, 64)])
    phone_number_alternate = StringField('Alternate Number')
    submit = SubmitField('Save')

class MessageForm(FlaskForm):
    sms_message = TextAreaField("SMS Messages", validators=[InputRequired()])
    phone_number = TextAreaField("Phone Numbers", validators=[InputRequired()])
    submit = SubmitField("Send Message")


class SelectGroupForm(FlaskForm):
    group = QuerySelectField(
        'Group',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(Group).order_by(Group.createdAt.desc()), get_pk=get_pk)
    submit = SubmitField("Select Group")


class MessageGroupForm(FlaskForm):
    sms_message = TextAreaField("SMS Messages", validators=[InputRequired()])
    phone_number = StringField("Phone Numbers")
    submit = SubmitField("Send Message")


class DisclaimerForm(FlaskForm):
    text = StringField("Text")
    submit = SubmitField("Save")


class NewGroupForm(FlaskForm):
    name = StringField("Name", validators=[InputRequired()])
    submit = SubmitField("Add")


class NewStaffForm(FlaskForm):
    name = StringField("Name", validators=[InputRequired()])
    email = StringField("Email", validators=[InputRequired()])
    phone_number = StringField("Phone Number", validators=[InputRequired()])
    directorate = StringField("Directorate", validators=[InputRequired()])
    department = StringField("Department", validators=[InputRequired()])
    submit = SubmitField("Add")


class NewPatientForm(FlaskForm):
    name = StringField("Name", validators=[InputRequired()])
    email = StringField("Email")
    phone_number = StringField("Phone Number", validators=[InputRequired()])
    status = SelectField(
        validators=[DataRequired()], choices=[("confirmed", "CONFIRMED"), ("suspected", "SUSPECTED"),
                                              ("negative", "NEGATIVE")]
    )
    ward = StringField("Ward", validators=[InputRequired()])
    submit = SubmitField("Add")

app/sender/__init__.py
from app.sender.views import sender

app/sender/views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    flash,
    send_from_directory,
)
from flask_ckeditor import upload_success
from flask_login import (
    current_user,
    login_required,
)
import PIL, simplejson, traceback
from PIL import Image
from flask_rq import get_queue
from sqlalchemy import create_engine, String
from app.models.users import *
from app.sender.forms import *
from app.auth.forms import *
from app import db
from app.email import send_email
from app.models import User, Message
from app.auth.email import send_password_reset_email
from app.auth.admin_decorators import check_confirmed
from werkzeug import secure_filename
from app.lib.upload_file import uploadfile
from werkzeug.datastructures import FileStorage
import africastalking

from config import DevelopmentConfig

ALLOWED_EXTENSIONS = {"txt", "gif", "png", "jpg", "jpeg", "bmp", "rar", "zip", "7zip", "doc", "docx", "pdf"}

sender = Blueprint('sender', __name__)
username = "kutrrh-info"
api_key = "266144f52e14d1f7160ade314da1fa048aec186e9bd26e54dfd15134fa5e89f5"
africastalking.initialize(username, api_key)
db_URI = DevelopmentConfig.SQLALCHEMY_DATABASE_URI
engine = create_engine(db_URI)

sms = africastalking.SMS


@sender.route('/')
@login_required
@check_confirmed
def dashboard():
    """Admin dashboard page."""

    messagesCount = Message.query.count()
    messagesCountToday = Message.query.order_by(Message.createdAt.desc()).limit(5).count()

    return render_template(
        "sender/index.html", messagesCount=messagesCount, messagesCountToday=messagesCountToday)


@sender.route('/send_messages', methods=['post', 'get'])
@login_required
@check_confirmed
def send_messages():
    all_groups = Group.query.order_by(Group.createdAt.desc()).all()
    form = MessageForm()
    form2 = SelectGroupForm()
    if form.validate_on_submit():
        sms_message = request.form['sms_message']
        phone_number = request.form['phone_number']
        sender = "KUTRRH-INFO"

        pn = phone_number.split(',')
        pnn = ["+" + x.strip(' ') for x in pn]
        print(pnn)

        try:
            # That's it, hit send and we'll take care of the rest.
            response = sms.send(sms_message, pnn, sender)
            flash("SMS sent successfully", "success")
            print(response)
            my_values = response["SMSMessageData"]["Recipients"]
            for mv in my_values:
                new_message = Message(
                    sender_id=current_user.id,
                    sms_message=form.sms_message.data,
                    phone_number=mv["number"],
                    status=mv["status"]
                )
                db.session.add(new_message)
                db.session.commit()
        except Exception as e:
            print('Encountered an error while sending: %s' % str(e))
            flash("SMS not sent successfully", "danger")

        return redirect(url_for("sender.dashboard"))
    if form2.validate_on_submit():
        selected_group = form2.group.data
        return redirect(url_for("admin.send_messages_to_group", group_id=selected_group.group_id))
    return render_template('sender/send_messages.html', form=form, all_groups=all_groups, form2=form2)


@sender.route('/profile', methods=['post', 'get'])
@login_required
@check_confirmed
def profile():
    """Admin dashboard page."""

    form = ProfileForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        db.session.commit()
        return redirect(url_for('sender.profile'))
    return render_template('sender/user-profile-page.html', form=form)


@sender.route('/settings', methods=['post', 'get'])
@login_required
@check_confirmed
def settings():
    """Admin dashboard page."""

    if current_user.is_anonymous:
        return redirect(url_for('home.index'))
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.new_password.data
            db.session.add(current_user)
            db.session.commit()
            flash('Your password has been updated.', "success")
            return redirect(url_for('sender.dashboard'))
        else:
            flash('Original password is invalid.', "warning")
    return render_template('account/reset_password.html', form=form)


@sender.route("/sent_messages")
@login_required
@check_confirmed
def sent_messages():
    all_messages = Message.query.order_by(Message.createdAt.desc()).all()
    return render_template('sender/view_messages.html', all_messages=all_messages)


@sender.route("/files/<path:filename>")
def uploaded_files(filename):
    path = current_app.config["UPLOADS"]
    return send_from_directory(path, filename)


@sender.route("/upload", methods=["POST"])
def upload():
    f = request.files.get("file")
    # Add more validations here
    extension = f.filename.split(".")[1].lower()

    f.save(os.path.join("app/static/uploads", f.filename))
    url = url_for("admin.uploaded_files", filename=f.filename)
    return upload_success(url=url)  # return upload_success call


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def gen_file_name(filename):
    """
    If file was exist already, rename it and return a new name
    """

    i = 1
    while os.path.exists(os.path.join(current_app.config["UPLOAD_FOLDER"], filename)):
        name, extension = os.path.splitext(filename)
        filename = "%s_%s%s" % (name, str(i), extension)
        i += 1

    return filename


def create_thumbnail(image):
    try:
        base_width = 100
        img = Image.open(os.path.join(current_app.config["UPLOAD_FOLDER"], image))
        w_percent = base_width / float(img.size[0])
        h_size = int((float(img.size[1]) * float(w_percent)))
        img = img.resize((base_width, h_size), PIL.Image.ANTIALIAS)
        img.save(os.path.join(current_app.config["THUMBNAIL_FOLDER"], image))

        return True

    except:
        print(traceback.format_exc())
        return False


@sender.route("/upload/<p_table>/<c_table>/<id>", methods=["GET", "POST"])
def upload_image(p_table, c_table, id):
    if request.method == "POST":
        files = request.files["file"]

        if files:
            filename = secure_filename(files.filename)
            filename = gen_file_name(filename)
            mime_type = files.content_type
            p_model = User.get_class_by_tablename(p_table)

            if not allowed_file(files.filename):
                result = uploadfile(
                    name=filename,
                    table=c_table,
                    type=mime_type,
                    size=0,
                    not_allowed_msg="File type not allowed",
                )

            else:
                # save file to disk
                uploaded_file_path = os.path.join(
                    current_app.config["UPLOAD_FOLDER"], filename
                )
                files.save(uploaded_file_path)
                p_model = User.get_class_by_tablename(p_table)
                c_model = User.get_class_by_tablename(c_table)
                parent_table = p_model.query.filter_by(id=id).first_or_404()
                if parent_table.images.count() >= 5:
                    return "You cannot add more than 5 images", 400
                new_image = c_model(image_url=filename, job_listing_id=parent_table.id)
                db.session.add(new_image)
                db.session.commit()

                # create thumbnail after saving
                if mime_type.startswith("image"):
                    create_thumbnail(filename)

                # get file size after saving
                size = os.path.getsize(uploaded_file_path)

                # return json for js call back
                result = uploadfile(
                    name=filename, table=c_table, type=mime_type, size=size
                )

            return simplejson.dumps({"files": [result.get_file()]})

    if request.method == "GET":
        # get all file in ./data directory
        p_model = User.get_class_by_tablename(p_table)
        c_model = User.get_class_by_tablename(c_table)
        parent_table = p_model.query.filter_by(id=id).first_or_404()
        files = [
            f.image_url
            for f in c_model.query.filter_by(job_listing_id=parent_table.id).all()
            if os.path.isfile(
                os.path.join(current_app.config["UPLOAD_FOLDER"], f.image_url)
            )
        ]
        file_display = []

        for f in files:
            size = os.path.getsize(os.path.join(current_app.config["UPLOAD_FOLDER"], f))
            file_saved = uploadfile(name=f, size=size, table=c_table)
            file_display.append(file_saved.get_file())

        return simplejson.dumps({"files": file_display})

    return redirect(url_for("index"))


@sender.route("/delete_image/<table>/<string:filename>", methods=["DELETE"])
def delete_image(table, filename):
    file_path = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)
    file_thumb_path = os.path.join(current_app.config["THUMBNAIL_FOLDER"], filename)
    c_model = User.get_class_by_tablename(table)
    table = c_model.query.filter_by(image_url=filename).first_or_404()
    db.session.delete(table)
    db.session.commit()
    if os.path.exists(file_path):
        try:
            os.remove(file_path)

            if os.path.exists(file_thumb_path):
                os.remove(file_thumb_path)

            return simplejson.dumps({filename: "True"})
        except:
            return simplejson.dumps({filename: "False"})


# serve static files
@sender.route("/thumbnail/<string:filename>", methods=["GET"])
def get_thumbnail(filename):
    return send_from_directory(
        current_app.config["THUMBNAIL_FOLDER"], filename=filename
    )


@sender.route("/data/<string:filename>", methods=["GET"])

app/templates/sender/_notification.html
<div class="dropdown-menu" aria-labelledby="notificationDropdown">
    <div class="dropdown-header d-flex align-items-center justify-content-between">
        <p class="mb-0 font-weight-medium">New Notifications</p>
        <a href="javascript:;" class="text-muted">Clear all</a>
    </div>
    <div class="dropdown-body">
         {% for item in notifications %}
        <a href="{{url_for('applicant.view_applications')}}" class="dropdown-item">
            <div class="icon">
                <i data-feather="user-plus"></i>
            </div>
            <div class="content">
                <p>New notification</p>
                <p class="sub-text text-muted">2 sec ago</p>
            </div>
        </a>
        {% else %}
        <a href="javascript:;" class="dropdown-item">
            <div class="icon">
                <i data-feather="user-plus"></i>
            </div>
            <div class="content">
                <p>No new notification</p>
                <p class="sub-text text-muted">2 sec ago</p>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

app/templates/sender/reset_password.html
{% extends 'home/home_base.html' %}


{% block header %}{% endblock header %}
{% block home_content %}

<img class="center-image" src="{{ url_for('static', filename='home/img/tour_grid_15.jpg') }}" alt="">

<div class="container">
	<div class="login-fullpage">
		<div class="row">
			<div class="login-logo">
				<img class="center-image" src="{{ url_for('static', filename='home/img/tour_grid_8.jpg') }}" alt="">
			</div>
			<div class="col-xs-12 col-sm-7">
				<div class="f-login-content">
					<div class="f-login-header">
						<div class="f-login-title color-dr-blue-2">Password Reset</div>
						<div class="f-login-desc color-grey">Please enter your email for a password reset link</div>
					</div>
					<form action="{{url_for('account.reset_password_request')}}" class="f-login-form" method="POST">
						{{form.hidden_tag()}}
						<div class="input-style-1 b-50 type-2 color-5">
							<label for="" class="pb-1">Email: </label>
							{{form.email()}}
							{%for error in form.email.errors%}
								<span>{{error}}</span>
							{%endfor%}
						</div>
						<div class="input-style-1 b-50 type-2 color-5">

						</div>
						<div class="checkbox-group">
							<div>
								<p>Don't an account? <a href="{{url_for('account.choose_account_type')}}" class="color-dr-blue-2">Register now.</a></p>
							</div>
						</div>

						{{form.submit(class="login-btn c-button full b-60 bg-dr-blue-2 hv-dr-blue-2-o")}}

						<!-- <div class="row">
							<div class="col-xs-12 col-sm-6">
								<a href="#" class="c-button full b-60 bg-blue-7 hv-blue-7-o"><i class="fa fa-facebook"></i><span>login via facebook</span></a>
							</div>
							<div class="col-xs-12 col-sm-6">
								<a href="#" class="c-button full b-60 bg-blue-8 hv-blue-8-o"><i class="fa fa-twitter"></i><span>login via facebook</span></a>
							</div>
						</div> -->
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock home_content %}

{% block footer %}{% endblock footer %}

app/templates/sender/send_messages.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">

{% endblock %}

{% block content %}
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('sender.dashboard')}}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">SEND OUT NEW MESSAGE</li>
    </ol>
</nav>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="cmxform" method="post" action="{{url_for('sender.send_messages')}}">
                    {{form.hidden_tag()}}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>SMS Message *</label>
                                {{form.sms_message(placeholder="SMS Message", class="form-control", rows='10')}}
                                {%for error in form.sms_message.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Phone Number(s) *</label>
                                {{form.phone_number(placeholder="Phone Number(s)", class="form-control", rows='10')}}
                                {%for error in form.phone_number.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            {{form.submit(class="btn btn-primary mr-2 mb-2 mb-md-0 text-white")}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block scripts%}
    <script>
            $(function() {
      'use strict';

      if($('#datePicker').length) {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#datePicker').datepicker({
          format: "dd/mm/yyyy",
          todayHighlight: true,
          autoclose: true
        });


        $('#datePicker').datepicker('setDate', today);
      }
      if($('#datePicker2').length) {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#datePicker2').datepicker({
          format: "dd/mm/yyyy",
          todayHighlight: true,
          autoclose: true
        });

        $('#datePicker2').datepicker('setDate', today);
      }
    });
    </script>
{%  endblock %}

app/templates/sender/view_messages.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
    {{ super() }}
     <style>
    td.s{
        padding: 0 !important;
        border-top: none !important;
        vertical-align: initial;
    }
    </style>
    <!-- CORE CSS-->
    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">
    {{ super() }}
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ url_for('static', filename='vendors/prismjs/themes/prism.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/buttons/buttons.dataTables.min.css') }}">
    <!-- end plugin css for this page -->
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <nav class="page-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">VIEW</a></li>
                <li class="breadcrumb-item active" aria-current="page">All Messages</li>
            </ol>
        </nav>
        <div class="d-flex align-items-center flex-wrap text-nowrap">
            <a href="{{ url_for('sender.send_messages') }}" type="button" class="btn btn-primary">ADD MESSAGE</a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-baseline mb-lg-4">
                        <h6 class="card-title mb-0">All Messages</h6>
                    </div>
                    <p class="card-description"></p>

                    <div class="table-responsive">
                        <table id="dataTable" class="table table-hover mb-0">
                            <thead>
                                <tr>
                                    <th class="pt-0">#</th>
                                    <th class="pt-0">Date</th>
                                    <th class="pt-0">Message</th>
                                    <th class="pt-0">Phone Numbers</th>
                                    <th class="pt-0">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for message in all_messages %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>
                                        {{ moment(message.get_time()).format('MMMM Do YYYY, h:mm:ss a') }}
                                    </td>
                                    <td style="white-space: break-spaces;text-overflow: ellipsis;">{{ message.sms_message }}</td>
                                    <td style="white-space: nowrap;text-overflow: ellipsis;">{{ message.phone_number }}</td>
                                    <td>
                                        <span class="badge {% if message.status == 'Success' %}bg-success
                                            {% elif message.status == 'Sent' %}bg-primary
                                            {% else %}bg-danger{% endif %}">
                                            {{ message.status }}
                                        </span>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td><span style="color: #007bff;">No messages available</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
       <!-- plugin js for this page -->
<script src="{{ url_for('static', filename='vendors/prismjs/prism.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/clipboard/clipboard.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jquery-3.2.1.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/jszip.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/pdfmake.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/vfs_fonts.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/zamn/jquery.dataTables.js') }}"></script>
<script src="{{ url_for('static', filename='js/buttons/dataTables.buttons.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/buttons/buttons.html5.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>

<!-- end plugin js for this page -->

    <script>

        $(function () {
            'use strict';

            $(function () {
                $('#dataTable').DataTable({
                    "aLengthMenu": [
                        [10, 30, 50, -1],
                        [10, 30, 50, "All"]
                    ],
                    "iDisplayLength": 10,
                    "language": {
                        search: ""
                    },
                    dom: 'Bfrtip',
                    buttons: [
                        'copyHtml5',
                        'csvHtml5',
                        'pdfHtml5',
                        {
                            extend: 'excel',
                            messageTop: 'All The Applications.'
                        },
                    ]
                });
                $('#dataTable').each(function () {
                    var datatable = $(this);
                    // SEARCH - Add the placeholder for Search and Turn this into in-line form control
                    var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
                    search_input.attr('placeholder', 'Search');
                    search_input.removeClass('form-control-sm');
                    // LENGTH - Inline-Form control
                    var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
                    length_sel.removeClass('form-control-sm');
                });
            });

        });
    </script>
    <script>
        $(function () {
            'use strict';

            if ($('#datePickerExample').length) {
                var date = new Date();
                var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
                $('#datePickerExample').datepicker({
                    format: "dd/mm/yyyy",
                    todayHighlight: true,
                    autoclose: true
                });
                // var ub = new Date('{{user_dob}}');
                $('#datePickerExample').datepicker('setDate', today)
            }
        });
    </script>
{% endblock %}